baseURL = "http://example.org/"
languageCode = "en-us"
title = "Exactly Once"
theme = "hyde"
[params]
  layoutReverse = false
  description = 'On distributed systems by <a href="http://twitter.com/SzymonPobiega">@SzymonPobiega</a> and <a href="http://twitter.com/Masternak">@Masternak</a>'
