baseURL = "https://exactly-once.github.io/"
languageCode = "en-us"
title = "Exactly Once"
googleAnalytics = "UA-147074711-1"
theme = "hyde"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
[params]
  layoutReverse = false
  author = 'Tomek Masternak, Szymon Pobiega'
  description = 'On distributed systems by <a href="http://twitter.com/SzymonPobiega">@SzymonPobiega</a> and <a href="http://twitter.com/Masternak">@Masternak</a>'
